- hosts: appservers
  vars:
    nginx_port: 8080
    root_dir: /usr/share/nginx/html
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: copy html page
      ansible.builtin.template:
        src: files/index.html.j2
        dest: "{{root_dir}}/index.html"
      notify:
        - restart nginx
      become: yes

    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
